first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete')
]

first_project/first_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$',views.IndexView.as_view()),
    url(r'^first_app/',include('first_app.urls',namespace='first_app')),
    # url(r'^$',views.CBView.as_view()),
    # url(r'^$',views.index)
]

first_project/first_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("first_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

first_project/first_app/forms.py
# from django import forms
# from django.contrib.auth.models import User
# from first_app.models import UserProfileInfo

# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())

#     class Meta():
#         model = User
#         fields = ('username','email','password')

# class UserProfileInfoForm(forms.ModelForm):
#     class Meta():
#         model = UserProfileInfo
#         fields = ('portofolio_site','profile_pics')

# class NewUserForm(forms.ModelForm):
#     class Meta():
#         model = User
#         fields = '__all__'
# from django.core import validators


# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)

#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verify_email']

#         if email != vmail:
#             raise forms.ValidationError("MAKE SURE EMAILS MATCH!")

first_project/first_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models
# Create your views here.

# Original Function View:
#
# def index(request):
#     return render(request,'index.html')
#
#

# Pretty simple right?
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection!"
        return context

class SchoolListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    # context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'first_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ("name","principal","location")
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ("name","principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("first_app:list")


class CBView(View):
    def get(self,request):
        return HttpResponse('Class Based Views are Cool!')

first_project/first_app/templates/first_app/first_app_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/style.css">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><img src="static/images/logo.jpeg" alt="Crash" width="120px" height="50px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">

          {# Django Home Link / Admin Link / Register Link#}
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:list' %}">Schools</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:create' %}">Create School</a></li>
        </ul>

      </div>
    </nav>
    
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>



  </body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>

first_project/first_app/templates/first_app/school_confirm_delete.html
{% extends "first_app/first_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'first_app:detail' pk=school.pk%} ">Cancel</a>

</form>

{% endblock %}

first_project/first_app/templates/first_app/school_detail.html
{% extends "first_app/first_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>School Detail Page</h1>
    <h2>School details:</h2>
    <p>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>

    <h3>Srudents:</h3>

    {% for student in school_details.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}



</div>
<div class="container">
    <p><a class='btn btn-warning' href="{% url 'first_app:update' pk=school_details.pk %}">Update</a></p>

  </div>

{% endblock %}

first_project/first_app/templates/first_app/school_form.html
{% extends "first_app/first_app_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

first_project/first_app/templates/first_app/school_list.html
{% extends "first_app/first_app_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
    <ol>
        <h1>test</h1>
        {% for school in school_list %}
        <h2><li><a href="{{school.id}}/">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>

{% endblock %}

first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/style.css">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><img src="static/images/logo.jpeg" alt="Crash" width="120px" height="50px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">

          {# Django Home Link / Admin Link / Register Link#}
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:list' %}">Schools</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:create' %}">Create School</a></li>
        </ul>

      </div>
    </nav>
    
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>



  </body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</html>

first_project/templates/first_app/dummy.html
<!-- <!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Project</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"><link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Hello this is Django Projet!</h1>
    <h2>Here are your access record data: </h2>

    <div class="djangtwo">
        {% if access_records %}
        <table>
            <thead>
                <th>Site name</th>
                <th>Date Accessed</th>
            </thead>
            {% for acc in access_records %}
        <tr>
            <td>{{ acc.name }}</td>
            <td>{{ acc.date }}</td>
        </tr>

        {% endfor %}
        </table>
        {% else %}
        <p>NO ACCESS RECORD FOUND!</p>
        {% endif %}

    </div>

</body>
</html> -->

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <h1>Fill out the form</h1>
    <div class="container">
        <form method="POST">
            {{forms.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
        


    </div>
    
</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<div class="Hero">
    <h1>This is Index Page</h1>
    <h2>Here is your injected content: {{ injectme }}</h2>
</div>
{% endblock %}
            

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'first_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
{% load static %}

    {% if registered %}

    <h1>Thank your for your registration</h1>

    {% else %}

    <div class="jumbotron">
    <div class="container">
    <p></p>
    <h1>Register here</h1>
    <h3>Fill out the form!</h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" value="Register">


    </form>

        </div>
    </div>


    {% endif %}


{% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
{% load static %}

    {% if registered %}

    <h1>Thank your for your registration</h1>

    {% else %}
    <section class="hero is-warning">
    <div class="hero-body">
    <div class="container">
    <p></p>
    <h1>Register here</h1>
    <h3>Fill out the form!</h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" value="Register">


    </form>

        </div>
    </div>
</section>

    {% endif %}


{% endblock %}

first_project/templates/first_app/user.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}

    <h1>Welcome!</h1>
    <h1>This is a user!</h1>
    <div class="container">
        <h1>This is a user page</h1>

        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}

            <input type="submit" class="btn btn-primary" value="Submit">
        </form>

    </div>

{% endblock %}

    